userinfo:
  uid: ""
  longitude: ""
  latitude: ""
  station_id: ""
  city_number: ""
  api_version: ""
  app_version: ""
  applet_source: ""
  channel: ""
  app_client_id: ""
  sharer_uid: ""
  openid: ""
  h_5_source: ""
  device_token: ""

headers:
  ddmc_city_number: ""
  ddmc_build_version: ""
  ddmc_device_id: ""
  ddmc_station_id: ""
  ddmc_channel: ""
  ddmc_os_version: ""
  ddmc_app_client_id: ""
  cookie: ""
  ddmc_ip: ""
  ddmc_longitude: ""
  ddmc_latitude: ""
  ddmc_api_version: ""
  ddmc_uid: ""
  user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.18(0x1800123c) NetType/WIFI Language/zh_CN"
  referer: "https://servicewechat.com/wx1e113254eda17715/422/page-frame.html"